spring:
    ## rabbit mq properties
    rabbitmq:
        consumer:
             addresses: 10.198.13.253:5672
             userName: zhuguojin
             password: zhuguojin
             publisher-confirms: true
             virtual-host: / 
                                 