redis:
  host: 10.198.20.253
  port: 6379
  password: 123456
  timeout: 2000
  database: 0
  pool:
      maxActive: 300
      maxWait: 5000
      maxIdle: 100
      minIdle: 10
      testOnBorrow: true
  sentinel:
      ips: 10.198.20.253:26379 
  master:
      name: mymaster     
       
