redis:
  password: 123456
  pool:
      maxActive: 300
      maxWait: 5000
      maxIdle: 100
      minIdle: 10
      testOnBorrow: true
  sentinel:
      ips: 10.198.13.253:26379 
  master:
      name: mymaster     
       
