spring:
    ## rabbit mq properties
    rabbitmq:
        producer:    
            addresses: 10.198.20.253:5672
            userName: zhuguojin
            password: zhuguojin
            publisher-confirms: true
            virtual-host: /     
                                 